"""Wrap the URL-audit Markdown report as a Docusaurus docs page.

This keeps the human-readable audit report available on GitHub Pages without
requiring the scheduled audit workflow to commit generated files back to the
repository.
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path


FRONTMATTER = """---
id: url-audit
title: "URL audit"
sidebar_label: URL audit
description: "Latest EyeDataHub source-link audit generated by GitHub Actions."
---

"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--report", default="hub/audit/url_report.md")
    ap.add_argument("--json", default="hub/audit/url_report.json")
    ap.add_argument("--out", default="website/docs/url-audit.md")
    ap.add_argument("--static-json", default="website/static/url_report.json")
    args = ap.parse_args()

    report_path = Path(args.report)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if report_path.exists():
        body = report_path.read_text(encoding="utf-8")
    else:
        body = (
            "# EyeDataHub URL Audit Report\n\n"
            "No URL audit report has been generated yet. Run "
            "`python -m hub.audit.verify_urls` to create one.\n"
        )

    note = (
        "\n\n:::note\n"
        "This page is regenerated by the GitHub Actions URL-audit workflow. "
        "Automated reachability does not imply dataset license compatibility, "
        "clinical validity, deidentification adequacy, or permission to reuse data. "
        "`no_bot_allowed` means the source host blocked automated probes even "
        "though manually checked browser links were healthy; it should not be "
        "interpreted as a dead source URL.\n"
        ":::\n\n"
    )
    out_path.write_text(FRONTMATTER + body + note, encoding="utf-8")

    json_path = Path(args.json)
    static_json = Path(args.static_json)
    if json_path.exists():
        static_json.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(json_path, static_json)

    print(f"Wrote {out_path}")
    if json_path.exists():
        print(f"Copied {json_path} -> {static_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
